services:
  - type: web
    name: carboniq-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: carboniq-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://group9-carbon-iq-8hdo.vercel.app,https://group9-carboniq.onrender.com

databases:
  - name: carboniq-db
    plan: free
